import { MonthData } from "@/types/expense";

// Placeholder data — será reemplazado con los datos reales de los PDFs
export const expensasData: MonthData[] = [
  {
    month: "2025-05",
    label: "Mayo 2025",
    total: 285000,
    items: [
      { category: "personal", description: "Sueldos encargado", amount: 95000 },
      { category: "personal", description: "Cargas sociales", amount: 38000 },
      { category: "servicios", description: "Gas", amount: 18000 },
      { category: "servicios", description: "Electricidad partes comunes", amount: 12000 },
      { category: "servicios", description: "Agua", amount: 8500 },
      { category: "mantenimiento", description: "Ascensor mantenimiento", amount: 22000 },
      { category: "mantenimiento", description: "Bomba de agua reparación", amount: 15000 },
      { category: "limpieza", description: "Productos de limpieza", amount: 6500 },
      { category: "seguros", description: "Seguro edificio", amount: 18000 },
      { category: "seguros", description: "ART", amount: 12000 },
      { category: "administracion", description: "Honorarios administración", amount: 25000 },
      { category: "impuestos", description: "ABL", amount: 8000 },
      { category: "fondo-reserva", description: "Fondo de reserva", amount: 7000 },
    ],
  },
  {
    month: "2025-06",
    label: "Junio 2025",
    total: 310000,
    items: [
      { category: "personal", description: "Sueldos encargado", amount: 98000 },
      { category: "personal", description: "Cargas sociales", amount: 39000 },
      { category: "servicios", description: "Gas", amount: 25000 },
      { category: "servicios", description: "Electricidad partes comunes", amount: 14000 },
      { category: "servicios", description: "Agua", amount: 9000 },
      { category: "mantenimiento", description: "Ascensor mantenimiento", amount: 22000 },
      { category: "mantenimiento", description: "Pintura hall", amount: 18000 },
      { category: "limpieza", description: "Productos de limpieza", amount: 7000 },
      { category: "seguros", description: "Seguro edificio", amount: 19000 },
      { category: "seguros", description: "ART", amount: 12500 },
      { category: "administracion", description: "Honorarios administración", amount: 28000 },
      { category: "impuestos", description: "ABL", amount: 8500 },
      { category: "fondo-reserva", description: "Fondo de reserva", amount: 10000 },
    ],
  },
  {
    month: "2025-07",
    label: "Julio 2025",
    total: 345000,
    items: [
      { category: "personal", description: "Sueldos encargado", amount: 105000 },
      { category: "personal", description: "Cargas sociales", amount: 42000 },
      { category: "personal", description: "Aguinaldo proporcional", amount: 25000 },
      { category: "servicios", description: "Gas", amount: 28000 },
      { category: "servicios", description: "Electricidad partes comunes", amount: 15000 },
      { category: "servicios", description: "Agua", amount: 9500 },
      { category: "mantenimiento", description: "Ascensor mantenimiento", amount: 23000 },
      { category: "limpieza", description: "Productos de limpieza", amount: 7500 },
      { category: "seguros", description: "Seguro edificio", amount: 20000 },
      { category: "seguros", description: "ART", amount: 13000 },
      { category: "administracion", description: "Honorarios administración", amount: 30000 },
      { category: "impuestos", description: "ABL", amount: 9000 },
      { category: "fondo-reserva", description: "Fondo de reserva", amount: 18000 },
    ],
  },
];
