import { MonthData } from "@/types/expense";

// Datos reales extraídos de las liquidaciones de Andrade Inmobiliaria
// Consorcio de Propietarios Garibaldi 407/411, San Isidro
// UF 26 = DIEZ, Gonzalo (1° A, cochera 21, 6.40%)

export const expensasData: MonthData[] = [
  {
    month: "2025-07",
    label: "Julio 2025",
    total: 1494046.54,
    expensasA: 2700000,
    ufDiez: 172800,
    items: [
      { category: "sueldos", description: "Sueldo Junio 2025 – López Ayala", amount: 303004 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 06/2025", amount: 279930.05 },
      { category: "cargas-sociales", description: "FATERYH 06/2025", amount: 45221.11 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 06/2025", amount: 3114.59 },
      { category: "cargas-sociales", description: "SUTERH 06/2025", amount: 28031.27 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 3/2025 Cuota 1", amount: 274051.21 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Junio", amount: 126744 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Junio", amount: 68000 },
      { category: "mantenimiento", description: "Claudio Ginestar – Jardinería Mayo", amount: 60000 },
      { category: "mantenimiento", description: "Claudio Ginestar – Jardinería Junio", amount: 60000 },
      { category: "reparaciones", description: "Jose Olivas – Arreglo filtración interna", amount: 20000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta", amount: 30000 },
      { category: "gastos-bancarios", description: "Imp. Ley 25.413 Créditos", amount: 17302.93 },
      { category: "gastos-bancarios", description: "Imp. Ley 25.413 Débitos", amount: 11191.89 },
      { category: "gastos-bancarios", description: "Suscripción Periódico Acción", amount: 5930 },
      { category: "gastos-bancarios", description: "IVA + Percep. IIBB + Multa cheque + Com.", amount: 31907.5 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Junio", amount: 29617.99 },
      { category: "administracion", description: "Honorarios Administración Junio", amount: 100000 },
    ],
  },
  {
    month: "2025-08",
    label: "Agosto 2025",
    total: 2589246.24,
    expensasA: 2700000,
    ufDiez: 172800,
    items: [
      { category: "sueldos", description: "Sueldo Julio 2025 – López Ayala", amount: 309908 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 07/2025", amount: 177978.35 },
      { category: "cargas-sociales", description: "FATERYH 07/2025", amount: 28944.77 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 07/2025", amount: 1980.24 },
      { category: "cargas-sociales", description: "SUTERH 07/2025", amount: 13664.22 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 199817.46 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Julio", amount: 126744 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 4/2025 Cuota 1", amount: 298496.78 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Julio", amount: 60000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Julio", amount: 71000 },
      { category: "mantenimiento", description: "Carlos Llantoy – Reparación revoques y cielo raso (hierros oxidados)", amount: 550000 },
      { category: "mantenimiento", description: "Corralón Bascioni – Materiales reparación", amount: 150000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta", amount: 30000 },
      { category: "gastos-bancarios", description: "Imp. Ley 25.413 + IVA + Percep. IIBB", amount: 48498.8 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral consorcio Cuota 1", amount: 178991.63 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Julio", amount: 42844.12 },
      { category: "administracion", description: "Honorarios Administración Julio", amount: 200000 },
    ],
  },
  {
    month: "2025-09",
    label: "Septiembre 2025",
    total: 3629453.72,
    expensasA: 2600000,
    ufDiez: 167248,
    items: [
      { category: "sueldos", description: "Sueldo Agosto 2025 – López Ayala", amount: 313699 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 08/2025", amount: 180195.43 },
      { category: "cargas-sociales", description: "FATERYH 08/2025", amount: 29304.45 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 08/2025", amount: 2004.47 },
      { category: "cargas-sociales", description: "SUTERH 08/2025", amount: 18040.23 },
      { category: "servicios-publicos", description: "AySA Servicios Generales (2 facturas)", amount: 1038820.39 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 4/2025 Cuota 2", amount: 223614.93 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Agosto", amount: 146000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Agosto", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Agosto", amount: 72000 },
      { category: "mantenimiento", description: "Nortel – Reparación portón (desmontar, cambiar rodamientos, motor, cremalleras)", amount: 410000 },
      { category: "mantenimiento", description: "Nortel – Cambio sensor/barrera infrarroja resistente a lluvias", amount: 198000 },
      { category: "mantenimiento", description: "Nortel – Adicionales transformador 24v barrera nueva", amount: 75000 },
      { category: "mantenimiento", description: "Pinturería Caporaso – Pintura casablanca 20Lt", amount: 124553.13 },
      { category: "reparaciones", description: "Carlos Llantoy – Pintura cielo raso por humedad UF25", amount: 200000 },
      { category: "reparaciones", description: "Ferretería Sevilla – Sellador manchas", amount: 11000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 102386.86 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral consorcio Cuota 1", amount: 178991.63 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Agosto", amount: 25843.2 },
      { category: "administracion", description: "Honorarios Administración Agosto", amount: 200000 },
    ],
  },
  {
    month: "2025-10",
    label: "Octubre 2025",
    total: 2032702.5,
    expensasA: 2600000,
    ufDiez: 166148,
    items: [
      { category: "sueldos", description: "Sueldo Septiembre 2025 – López Ayala", amount: 318643 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 09/2025", amount: 183078.17 },
      { category: "cargas-sociales", description: "FATERYH 09/2025", amount: 29773.32 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 09/2025", amount: 2036.06 },
      { category: "cargas-sociales", description: "SUTERH 09/2025", amount: 18324.51 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 491245.13 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 4/2025 Cuota 2", amount: 194275.97 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Septiembre", amount: 146000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Septiembre", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Septiembre", amount: 75000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 89491.51 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral consorcio Cuota 1", amount: 178991.63 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Septiembre", amount: 25843.2 },
      { category: "administracion", description: "Honorarios Administración Septiembre", amount: 200000 },
    ],
  },
  {
    month: "2025-11",
    label: "Noviembre 2025",
    total: 2806922.76,
    expensasA: 2600000,
    ufDiez: 166400,
    items: [
      { category: "sueldos", description: "Sueldo Octubre 2025 – López Ayala", amount: 337037 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 10/2025", amount: 193663.43 },
      { category: "cargas-sociales", description: "FATERYH 10/2025", amount: 31615.96 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 10/2025", amount: 2153.59 },
      { category: "cargas-sociales", description: "SUTERH 10/2025", amount: 19382.31 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 436243.86 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 5/2025 Cuota 2", amount: 197209.84 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Octubre", amount: 146000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Septiembre", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Octubre", amount: 79000 },
      { category: "mantenimiento", description: "Carlos Llantoy – Reparación revoques, sellado grietas, pintura palier 1er cuerpo (Cuota 1/2)", amount: 650000 },
      { category: "mantenimiento", description: "EVER SAFE – Postes vial delimitador reflectivo", amount: 43654 },
      { category: "mantenimiento", description: "Casa Bascioni + Caporaso + Ferretería – Materiales pintura", amount: 274389.25 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 90730.32 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Octubre", amount: 25843.2 },
      { category: "administracion", description: "Honorarios Administración Octubre", amount: 200000 },
    ],
  },
  {
    month: "2025-12",
    label: "Diciembre 2025",
    total: 2832591.17,
    expensasA: 2600000,
    ufDiez: 166400,
    items: [
      { category: "sueldos", description: "Sueldo Noviembre 2025 – López Ayala", amount: 341804 },
      { category: "sueldos", description: "SAC 2do Semestre 2025 – López Ayala", amount: 209713 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 11/2025", amount: 196423.79 },
      { category: "cargas-sociales", description: "FATERYH 11/2025", amount: 32069.62 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 11/2025", amount: 2184.05 },
      { category: "cargas-sociales", description: "SUTERH 11/2025", amount: 19656.45 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 436243.86 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 5/2025 Cuota 1", amount: 308700.24 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Noviembre", amount: 146000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Noviembre", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Noviembre", amount: 82000 },
      { category: "mantenimiento", description: "Carlos Llantoy – Pintura palier 1er cuerpo (Cuota 2/2)", amount: 650000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 101952.96 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Noviembre", amount: 25843.2 },
      { category: "administracion", description: "Honorarios Administración Noviembre", amount: 200000 },
    ],
  },
  {
    month: "2026-01",
    label: "Enero 2026",
    total: 3259227.41,
    expensasA: 3100000,
    ufDiez: 197300,
    items: [
      { category: "sueldos", description: "Sueldo Diciembre 2025 – López Ayala", amount: 341804 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 12/2025", amount: 339502.5 },
      { category: "cargas-sociales", description: "FATERYH 12/2025", amount: 51701.33 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 12/2025", amount: 3524.07 },
      { category: "cargas-sociales", description: "SUTERH 12/2025", amount: 31716.63 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 379306.08 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 6/2025 Cuota 2", amount: 348016.42 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Diciembre", amount: 146000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Noviembre", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Diciembre", amount: 86000 },
      { category: "mantenimiento", description: "Carlos Llantoy – Reparación vereda frente edificio", amount: 350000 },
      { category: "mantenimiento", description: "VIRS Ascensores – Reparación caja fermator variador frecuencia ascensor Nº2", amount: 434390 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 106097.7 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral Póliza 102.047.505 Cuota 6", amount: 178991 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral Póliza 102.064.598 Cuota 1", amount: 123470.65 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Diciembre", amount: 38707.03 },
      { category: "administracion", description: "Honorarios Administración Diciembre", amount: 220000 },
    ],
  },
  {
    month: "2026-02",
    label: "Febrero 2026",
    total: 2831707.28,
    expensasA: 3313000,
    ufDiez: 212032,
    items: [
      { category: "sueldos", description: "Sueldo Enero 2026 – López Ayala", amount: 299212 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 01/2026", amount: 242667.54 },
      { category: "cargas-sociales", description: "FATERYH 01/2026", amount: 40608.87 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 01/2026", amount: 2082.87 },
      { category: "cargas-sociales", description: "SUTERH 01/2026", amount: 18745.87 },
      { category: "cargas-sociales", description: "Maximiliano Nicolás Oliver – Honorarios convenio de pago", amount: 59261.53 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 379306.08 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 6/2025 Cuota 2", amount: 188220.96 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Enero 2026", amount: 150000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Febrero", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Enero", amount: 89000 },
      { category: "abonos-servicios", description: "Solución Laboral – Suplente limpieza", amount: 647850 },
      { category: "mantenimiento", description: "O.J.Consulting – Flete baldosones", amount: 25000 },
      { category: "mantenimiento", description: "Pietras – Baldosones 40x40 + flete", amount: 60000 },
      { category: "mantenimiento", description: "Nortel – Visita técnica revisión portón garaje", amount: 40000 },
      { category: "mantenimiento", description: "Casa Bascioni – Materiales reparación (arena, piedra, cemento)", amount: 50600 },
      { category: "mantenimiento", description: "Ferretería Sevilla – Materiales adicionales", amount: 17600 },
      { category: "mantenimiento", description: "GS Sanitarios – Flotante mecánico tanque Bloque A", amount: 34500 },
      { category: "mantenimiento", description: "Carlos Llantoy – Arreglo tanque bloque A", amount: 80000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 107051.56 },
      { category: "administracion", description: "Honorarios Administración Enero 2026", amount: 220000 },
    ],
  },
  {
    month: "2026-03",
    label: "Marzo 2026",
    total: 3670464.62,
    expensasA: 3700000,
    ufDiez: 236799,
    items: [
      { category: "sueldos", description: "Sueldo Febrero 2026 – López Ayala", amount: 288811 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 02/2026", amount: 239995.97 },
      { category: "cargas-sociales", description: "FATERYH 02/2026", amount: 31156.38 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 02/2026", amount: 2020.77 },
      { category: "cargas-sociales", description: "SUTERH 02/2026", amount: 18186.91 },
      { category: "cargas-sociales", description: "FATERYH (OSPERYH, SUTERH, etc) – Cuota 1/2", amount: 244882.37 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 76608.85 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 6/2025 Cuota 2", amount: 220057.25 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Febrero", amount: 150000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Marzo", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Febrero", amount: 94000 },
      { category: "abonos-servicios", description: "EXTINCENTER – Recarga matafuegos Cuota 1/2", amount: 457443.61 },
      { category: "mantenimiento", description: "Iluminadores SRL – Trabajos electricista, cambio conectores dulux a LED, dicroicas, luminarias emergencia, cocheras (Cuota 1/3)", amount: 716666.67 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 122867.43 },
      { category: "seguros-gastos", description: "Met Life – Seguro Póliza 102.047.505 Cuotas 3+4", amount: 357982 },
      { category: "seguros-gastos", description: "Met Life – Seguro Póliza 102.064.597 Cuotas 2+3", amount: 246941.3 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Febrero", amount: 42844.12 },
      { category: "seguros-gastos", description: "DANUBIO – Ambo uniforme empleada", amount: 60000 },
      { category: "administracion", description: "Honorarios Administración Febrero 2026", amount: 220000 },
    ],
  },
];
