import { MonthData } from "@/types/expense";

// Datos reales extraídos de las liquidaciones de Andrade Inmobiliaria
// Consorcio de Propietarios Garibaldi 407/411, San Isidro
// UF 26 = DIEZ, Gonzalo (1° A, cochera 21, 6.40%)

export const expensasData: MonthData[] = [
  {
    month: "2025-03",
    label: "Marzo 2025",
    total: 2240951.11,
    expensasA: 2000000,
    items: [
      { category: "sueldos", description: "Sueldo Enero 2025 (Vacaciones) – López Ayala", amount: 251099 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 01/2025", amount: 143789.21 },
      { category: "cargas-sociales", description: "FATERYH 01/2025", amount: 21982.28 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 01/2025", amount: 1604.46 },
      { category: "cargas-sociales", description: "SUTERH 01/2025", amount: 14440.18 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 753095.59 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 1/2025 Cuota 1", amount: 298496.78 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Enero", amount: 91840 },
      { category: "abonos-servicios", description: "Solución Laboral – Suplente limpieza", amount: 348150 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 61768.61 },
      { category: "seguros-gastos", description: "Gráfica Solar – Copia y escaneo de plano PH", amount: 14000 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral consorcio Cuota 3", amount: 137685 },
      { category: "seguros-gastos", description: "Cerrajería Mainservice – Copia de llave", amount: 3000 },
      { category: "administracion", description: "Honorarios Administración Enero 2025", amount: 100000 },
    ],
  },
  {
    month: "2025-04",
    label: "Abril 2025",
    total: 1367027.21,
    expensasA: 2000000,
    items: [
      { category: "sueldos", description: "Sueldo Febrero 2025 – López Ayala", amount: 254865 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 02/2025", amount: 146135.63 },
      { category: "cargas-sociales", description: "FATERYH 02/2025", amount: 28826.17 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 02/2025", amount: 1628.53 },
      { category: "cargas-sociales", description: "SUTERH 02/2025", amount: 14656.77 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 238347.27 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 1/2025 Cuota 2", amount: 306737.10 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Febrero", amount: 105620 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Marzo + poda enredadera", amount: 80000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 62519.51 },
      { category: "seguros-gastos", description: "Patagonia – Artículos de limpieza Febrero", amount: 27691.23 },
      { category: "administracion", description: "Honorarios Administración Febrero 2025", amount: 100000 },
    ],
  },
  {
    month: "2025-05",
    label: "Mayo 2025",
    total: 2540596.75,
    expensasA: 3400000,
    items: [
      { category: "sueldos", description: "Sueldo Marzo 2025 – López Ayala", amount: 303004 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 03/2025", amount: 173819.45 },
      { category: "cargas-sociales", description: "FATERYH 03/2025", amount: 28289.64 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 03/2025", amount: 1936.13 },
      { category: "cargas-sociales", description: "SUTERH 03/2025", amount: 17425.14 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 238347.27 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 2/2025 Cuota 1", amount: 217762.53 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Febrero", amount: 105620 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Marzo", amount: 60000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Marzo", amount: 59000 },
      { category: "abonos-servicios", description: "EXTINCENTER – Matafuegos Cuota 1/3", amount: 358338.03 },
      { category: "abonos-servicios", description: "EXTINCENTER – Adicionales cartelería y soportes Cuota 1/3", amount: 89175.13 },
      { category: "mantenimiento", description: "Claudio Ginestar – Fijar enredadera caída en paller", amount: 60000 },
      { category: "mantenimiento", description: "Alport – Reparación frente porteros eléctrico por quemadura", amount: 205700 },
      { category: "mantenimiento", description: "Iluminadores SRL – Trabajos electricista varios (Cuota 1/3)", amount: 294229.81 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 65904.93 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral consorcio Cuota 4", amount: 137685 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Marzo", amount: 24359.69 },
      { category: "administracion", description: "Honorarios Administración Marzo 2025", amount: 100000 },
    ],
  },
  {
    month: "2025-06",
    label: "Junio 2025",
    total: 3842839.27,
    expensasA: 3400000,
    items: [
      { category: "sueldos", description: "Sueldo Abril 2025 – López Ayala", amount: 303004 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 04/2025", amount: 173895.45 },
      { category: "cargas-sociales", description: "FATERYH 04/2025", amount: 28289.64 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 04/2025", amount: 1936.13 },
      { category: "cargas-sociales", description: "SUTERH 04/2025", amount: 17425.14 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 1035450.39 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Abril", amount: 105620 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 2/2025 Cuota 2", amount: 220044.03 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Abril", amount: 60000 },
      { category: "abonos-servicios", description: "EXTINCENTER – Matafuegos Cuota 2/3", amount: 358338.03 },
      { category: "abonos-servicios", description: "EXTINCENTER – Adicionales cartelería y soportes Cuota 2/3", amount: 89175.13 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Abril", amount: 62000 },
      { category: "mantenimiento", description: "Carlos Llantoy – Pintura rejas al frente", amount: 450000 },
      { category: "mantenimiento", description: "Ferretería El Parque – Materiales pintura rejas", amount: 10300 },
      { category: "mantenimiento", description: "Pinturería Prestigio – Pintura Sintético Kern gris + aguarrás", amount: 97155.24 },
      { category: "mantenimiento", description: "Alport – Restaurar porteros visores (módulo + monitores)", amount: 230596 },
      { category: "mantenimiento", description: "Pinturería Prestigio – Pintura Sintético Kern beige", amount: 23042.23 },
      { category: "mantenimiento", description: "Pinturería Prestigio – Silicona + fijador", amount: 18819.25 },
      { category: "mantenimiento", description: "Ferretería Sevilla – Tarugos, tornillos, aguarrás", amount: 9800 },
      { category: "mantenimiento", description: "De Todo – Tapa 30x30 acero inoxidable", amount: 24020 },
      { category: "mantenimiento", description: "Carlos Llantoy – Cambio puertas de gas y agua", amount: 130000 },
      { category: "mantenimiento", description: "Puerta de Gas Aprobada 22x65 con Marco", amount: 50490 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 79910.41 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral consorcio Cuota 5", amount: 137685 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Abril", amount: 25843.2 },
      { category: "administracion", description: "Honorarios Administración Abril 2025", amount: 100000 },
    ],
  },
  {
    month: "2025-07",
    label: "Julio 2025",
    total: 3914530.73,
    expensasA: 2800000,
    items: [
      { category: "sueldos", description: "Sueldo Mayo 2025 – López Ayala (incluye adicionales)", amount: 487433 },
      { category: "cargas-sociales", description: "Cargas Sociales 05/2025", amount: 221598.36 },
      { category: "abonos-servicios", description: "EDENOR + VIRS + Eco Norte + Claudio Ginestar + otros servicios", amount: 904833.12 },
      { category: "mantenimiento", description: "Obras varias: revoques, pintura, porteros, materiales", amount: 1935164.75 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 99744.85 },
      { category: "seguros-gastos", description: "Met Life + Patagonia limpieza", amount: 165756.65 },
      { category: "administracion", description: "Honorarios Administración Mayo 2025", amount: 100000 },
    ],
  },
  {
    month: "2025-08",
    label: "Agosto 2025",
    total: 1494046.54,
    expensasA: 2700000,
    items: [
      { category: "sueldos", description: "Sueldo Junio 2025 – López Ayala", amount: 303004 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 06/2025", amount: 279930.05 },
      { category: "cargas-sociales", description: "FATERYH 06/2025", amount: 45221.11 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 06/2025", amount: 3114.59 },
      { category: "cargas-sociales", description: "SUTERH 06/2025", amount: 28031.27 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 3/2025 Cuota 1", amount: 274051.21 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Junio", amount: 126744 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Junio", amount: 68000 },
      { category: "mantenimiento", description: "Claudio Ginestar – Jardinería Mayo", amount: 60000 },
      { category: "mantenimiento", description: "Claudio Ginestar – Jardinería Junio", amount: 60000 },
      { category: "reparaciones", description: "Jose Olivas – Arreglo filtración interna", amount: 20000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta", amount: 30000 },
      { category: "gastos-bancarios", description: "Imp. Ley 25.413 Créditos", amount: 17302.93 },
      { category: "gastos-bancarios", description: "Imp. Ley 25.413 Débitos", amount: 11191.89 },
      { category: "gastos-bancarios", description: "Suscripción Periódico Acción", amount: 5930 },
      { category: "gastos-bancarios", description: "IVA + Percep. IIBB + Multa cheque + Com.", amount: 31907.5 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Junio", amount: 29617.99 },
      { category: "administracion", description: "Honorarios Administración Junio", amount: 100000 },
    ],
  },
  {
    month: "2025-09",
    label: "Septiembre 2025",
    total: 2589246.24,
    expensasA: 2700000,
    items: [
      { category: "sueldos", description: "Sueldo Julio 2025 – López Ayala", amount: 309908 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 07/2025", amount: 177978.35 },
      { category: "cargas-sociales", description: "FATERYH 07/2025", amount: 28944.77 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 07/2025", amount: 1980.24 },
      { category: "cargas-sociales", description: "SUTERH 07/2025", amount: 13664.22 },
      { category: "cargas-sociales", description: "SUTERH Adicional cuota 07/2025", amount: 4157.94 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 199817.46 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Julio", amount: 126744 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 4/2025 Cuota 1", amount: 212683.38 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Julio", amount: 60000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Julio", amount: 71000 },
      { category: "mantenimiento", description: "Carlos Llantoy – Reparación revoques y cielo raso (hierros oxidados)", amount: 550000 },
      { category: "mantenimiento", description: "Corralón Bascioni – Materiales reparación", amount: 150000 },
      { category: "mantenimiento", description: "Nortel – Reparación portón garaje (materiales y mano de obra)", amount: 357600 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta", amount: 30000 },
      { category: "gastos-bancarios", description: "Imp. Ley 25.413 + IVA + Percep. IIBB", amount: 51923.76 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Julio", amount: 42844.12 },
      { category: "administracion", description: "Honorarios Administración Julio", amount: 200000 },
    ],
  },
  {
    month: "2025-10",
    label: "Octubre 2025",
    total: 3629453.72,
    expensasA: 2600000,
    items: [
      { category: "sueldos", description: "Sueldo Agosto 2025 – López Ayala", amount: 313699 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 08/2025", amount: 180195.43 },
      { category: "cargas-sociales", description: "FATERYH 08/2025", amount: 29304.45 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 08/2025", amount: 2004.47 },
      { category: "cargas-sociales", description: "SUTERH 08/2025", amount: 18040.23 },
      { category: "servicios-publicos", description: "AySA Servicios Generales (2 facturas)", amount: 1038820.39 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 4/2025 Cuota 2", amount: 223614.93 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Agosto", amount: 146000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Agosto", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Agosto", amount: 72000 },
      { category: "mantenimiento", description: "Nortel – Reparación portón (desmontar, cambiar rodamientos, motor, cremalleras)", amount: 410000 },
      { category: "mantenimiento", description: "Nortel – Cambio sensor/barrera infrarroja resistente a lluvias", amount: 198000 },
      { category: "mantenimiento", description: "Nortel – Adicionales transformador 24v barrera nueva", amount: 75000 },
      { category: "mantenimiento", description: "Pinturería Caporaso – Pintura casablanca 20Lt", amount: 124553.13 },
      { category: "mantenimiento", description: "Carlos Llantoy – Pintura cielo raso por humedad UF25", amount: 200000 },
      { category: "mantenimiento", description: "Ferretería Sevilla – Sellador manchas", amount: 11000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 102386.86 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral consorcio Cuota 1", amount: 178991.63 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Agosto", amount: 25843.2 },
      { category: "administracion", description: "Honorarios Administración Agosto", amount: 200000 },
    ],
  },
  {
    month: "2025-11",
    label: "Noviembre 2025",
    total: 2032702.50,
    expensasA: 2600000,
    items: [
      { category: "sueldos", description: "Sueldo Septiembre 2025 – López Ayala", amount: 318643 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 09/2025", amount: 183078.17 },
      { category: "cargas-sociales", description: "FATERYH 09/2025", amount: 29773.32 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 09/2025", amount: 2036.06 },
      { category: "cargas-sociales", description: "SUTERH 09/2025", amount: 18324.51 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 491245.13 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 4/2025 Cuota 2", amount: 194275.97 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Septiembre", amount: 146000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Septiembre", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Septiembre", amount: 75000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 89491.51 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral consorcio Cuota 1", amount: 178991.63 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Septiembre", amount: 25843.2 },
      { category: "administracion", description: "Honorarios Administración Septiembre", amount: 200000 },
    ],
  },
  {
    month: "2025-12",
    label: "Diciembre 2025",
    total: 2806922.76,
    expensasA: 2600000,
    items: [
      { category: "sueldos", description: "Sueldo Octubre 2025 – López Ayala", amount: 337037 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 10/2025", amount: 193663.43 },
      { category: "cargas-sociales", description: "FATERYH 10/2025", amount: 31615.96 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 10/2025", amount: 2153.59 },
      { category: "cargas-sociales", description: "SUTERH 10/2025", amount: 19382.31 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 436243.86 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 5/2025 Cuota 2", amount: 197209.84 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Octubre", amount: 146000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Septiembre", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Octubre", amount: 79000 },
      { category: "mantenimiento", description: "Carlos Llantoy – Reparación revoques, sellado grietas, pintura palier 1er cuerpo (Cuota 1/2)", amount: 650000 },
      { category: "mantenimiento", description: "EVER SAFE – Postes vial delimitador reflectivo", amount: 43654 },
      { category: "mantenimiento", description: "Casa Bascioni + Caporaso + Ferretería – Materiales pintura", amount: 274389.25 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 90730.32 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Octubre", amount: 25843.2 },
      { category: "administracion", description: "Honorarios Administración Octubre", amount: 200000 },
    ],
  },
  {
    month: "2026-01",
    label: "Enero 2026",
    total: 2832591.17,
    expensasA: 2600000,
    items: [
      { category: "sueldos", description: "Sueldo Noviembre 2025 – López Ayala", amount: 341804 },
      { category: "sueldos", description: "SAC 2do Semestre 2025 – López Ayala", amount: 209713 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 11/2025", amount: 196423.79 },
      { category: "cargas-sociales", description: "FATERYH 11/2025", amount: 32069.62 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 11/2025", amount: 2184.05 },
      { category: "cargas-sociales", description: "SUTERH 11/2025", amount: 19656.45 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 436243.86 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 5/2025 Cuota 1", amount: 308700.24 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Noviembre", amount: 146000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Noviembre", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Noviembre", amount: 82000 },
      { category: "mantenimiento", description: "Carlos Llantoy – Pintura palier 1er cuerpo (Cuota 2/2)", amount: 650000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 101952.96 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Noviembre", amount: 25843.2 },
      { category: "administracion", description: "Honorarios Administración Noviembre", amount: 200000 },
    ],
  },
  {
    month: "2026-02",
    label: "Febrero 2026",
    total: 3259227.41,
    expensasA: 3100000,
    items: [
      { category: "sueldos", description: "Sueldo Diciembre 2025 – López Ayala", amount: 341804 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 12/2025", amount: 339502.5 },
      { category: "cargas-sociales", description: "FATERYH 12/2025", amount: 51701.33 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 12/2025", amount: 3524.07 },
      { category: "cargas-sociales", description: "SUTERH 12/2025", amount: 31716.63 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 379306.08 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 6/2025 Cuota 2", amount: 348016.42 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Diciembre", amount: 146000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Noviembre", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Diciembre", amount: 86000 },
      { category: "mantenimiento", description: "Carlos Llantoy – Reparación vereda frente edificio", amount: 350000 },
      { category: "mantenimiento", description: "VIRS Ascensores – Reparación caja fermator variador frecuencia ascensor Nº2", amount: 434390 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 106097.7 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral Póliza 102.047.505 Cuota 6", amount: 178991 },
      { category: "seguros-gastos", description: "Met Life – Seguro integral Póliza 102.064.598 Cuota 1", amount: 123470.65 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Diciembre", amount: 38707.03 },
      { category: "administracion", description: "Honorarios Administración Diciembre", amount: 220000 },
    ],
  },
  {
    month: "2026-03",
    label: "Marzo 2026",
    total: 2831707.28,
    expensasA: 3313000,
    items: [
      { category: "sueldos", description: "Sueldo Enero 2026 – López Ayala", amount: 299212 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 01/2026", amount: 242667.54 },
      { category: "cargas-sociales", description: "FATERYH 01/2026", amount: 40608.87 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 01/2026", amount: 2082.87 },
      { category: "cargas-sociales", description: "SUTERH 01/2026", amount: 18745.87 },
      { category: "cargas-sociales", description: "Maximiliano Nicolás Oliver – Honorarios convenio de pago", amount: 59261.53 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 379306.08 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 6/2025 Cuota 2", amount: 188220.96 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Enero 2026", amount: 150000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Febrero", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Enero", amount: 89000 },
      { category: "abonos-servicios", description: "Solución Laboral – Suplente limpieza", amount: 647850 },
      { category: "mantenimiento", description: "O.J.Consulting – Flete baldosones", amount: 25000 },
      { category: "mantenimiento", description: "Pietras – Baldosones 40x40 + flete", amount: 60000 },
      { category: "mantenimiento", description: "Nortel – Visita técnica revisión portón garaje", amount: 40000 },
      { category: "mantenimiento", description: "Casa Bascioni – Materiales reparación (arena, piedra, cemento)", amount: 50600 },
      { category: "mantenimiento", description: "Ferretería Sevilla – Materiales adicionales", amount: 17600 },
      { category: "mantenimiento", description: "GS Sanitarios – Flotante mecánico tanque Bloque A", amount: 34500 },
      { category: "mantenimiento", description: "Carlos Llantoy – Arreglo tanque bloque A", amount: 80000 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 107051.56 },
      { category: "administracion", description: "Honorarios Administración Enero 2026", amount: 220000 },
    ],
  },
  {
    month: "2026-04",
    label: "Abril 2026",
    total: 3670464.62,
    expensasA: 3700000,
    items: [
      { category: "sueldos", description: "Sueldo Febrero 2026 – López Ayala", amount: 288811 },
      { category: "cargas-sociales", description: "AFIP F.931 SUSS / Cargas Sociales 02/2026", amount: 239995.97 },
      { category: "cargas-sociales", description: "FATERYH 02/2026", amount: 31156.38 },
      { category: "cargas-sociales", description: "FATERYH (SERACARH) 02/2026", amount: 2020.77 },
      { category: "cargas-sociales", description: "SUTERH 02/2026", amount: 18186.91 },
      { category: "cargas-sociales", description: "FATERYH (OSPERYH, SUTERH, etc) – Cuota 1/2", amount: 244882.37 },
      { category: "servicios-publicos", description: "AySA Servicios Generales", amount: 76608.85 },
      { category: "abonos-servicios", description: "EDENOR Bimestre 6/2025 Cuota 2", amount: 220057.25 },
      { category: "abonos-servicios", description: "VIRS Ascensores – Mantenimiento Febrero", amount: 150000 },
      { category: "abonos-servicios", description: "Claudio Ginestar – Jardinería Marzo", amount: 80000 },
      { category: "abonos-servicios", description: "Eco Norte Fumigaciones – Febrero", amount: 94000 },
      { category: "abonos-servicios", description: "EXTINCENTER – Recarga matafuegos Cuota 1/2", amount: 457443.61 },
      { category: "mantenimiento", description: "Iluminadores SRL – Trabajos electricista, cambio conectores dulux a LED, dicroicas, luminarias emergencia, cocheras (Cuota 1/3)", amount: 716666.67 },
      { category: "gastos-bancarios", description: "Com. mantenimiento cuenta + Imp. + IVA + Percep.", amount: 122867.43 },
      { category: "seguros-gastos", description: "Met Life – Seguro Póliza 102.047.505 Cuotas 3+4", amount: 357982 },
      { category: "seguros-gastos", description: "Met Life – Seguro Póliza 102.064.597 Cuotas 2+3", amount: 246941.3 },
      { category: "seguros-gastos", description: "Patagonia – Artículos limpieza Febrero", amount: 42844.12 },
      { category: "seguros-gastos", description: "DANUBIO – Ambo uniforme empleada", amount: 60000 },
      { category: "administracion", description: "Honorarios Administración Febrero 2026", amount: 220000 },
    ],
  },
];
